name: test
on: push

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
          cache: yarn
      - run: yarn install

  linters:
    needs: dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
          cache: yarn
      - run: yarn run linters

#  build:
#    runs-on: ubuntu-latest
#    needs: dependencies
#    steps:
#      - name: build
#        run: yarn build
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: [dependencies, build]
#    steps:
#      - name: deploy
#        run: yarn deploy
