name: test
on: push

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: dependencies
        run: yarn i

  linters:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - name: linters
        run: yarn linters

  build:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - name: build
        run: yarn build

  deploy:
    runs-on: ubuntu-latest
    needs: [dependencies, build]
    steps:
      - name: deploy
        run: yarn deploy
